downgrade buildkit-cache-dance action version to fix it, and add error handlign to delete stale cache step

diff --git a/.github/workflows/base-image.yml b/.github/workflows/base-image.yml
--- a/.github/workflows/base-image.yml
+++ b/.github/workflows/base-image.yml
@@ -108,14 +108,14 @@ jobs:
             --key "buildkit-${{ matrix.platform_base.tag_name }}-" \
             --json key -q '.[].key' | while read -r key; do
             echo "Deleting stale cache: $key"
-            gh cache delete "$key"
+            gh cache delete "$key" || echo "::warning::Failed to delete stale cache: $key"
           done
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Inject/extract cache mounts
         if: steps.cache.outputs.cache-hit != 'true'
-        uses: reproducible-containers/buildkit-cache-dance@v3.3.1
+        uses: reproducible-containers/buildkit-cache-dance@v3.1.2
         with:
           cache-map: |
             {
